### PR TITLE
chore: Removes c-j-j from CODEOWNERS

### PR DESCRIPTION
**Pull request by c-j-j**

### CODE REVIEW

**Comment by Geoff-Ford** [comment]
So cold

**Comment by Geoff-Ford** [comment]
Actually, you may as well remove GeorgianSorinMaxim too as he has gone

**Comment by c-j-j** [comment]
> Actually, you may as well remove GeorgianSorinMaxim too as he has gone

@Geoff-Ford done

**Review by Geoff-Ford — DISMISSED** [review]
:trollface:

**Review by aronshamash — APPROVED** [review]

**Review by Geoff-Ford — APPROVED** [review]

**Comment by Geoff-Ford** [comment]
Touche

**Pull request merged**
